name: 'Sonar Fork Analysis'
description: 'Analyse project with Sonar including external fork'
inputs:
  phase:
    description: 'Phase of the sonar analysis'
    required: true
runs:
  using: "composite"
  steps:
    - name: 'Prepare target artifact'
      if: ${{ inputs.phase == 'prepare' }}
      shell: bash
      run: find -iname "*target" -type d -exec tar -rf target.tar {} \+

    - name: 'Set groupId'
      if: inputs.phase == 'prepare'
      shell: bash
      run: echo "group_id=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.groupId | tr . /)" >> "$GITHUB_ENV"

    - name: 'Prepare repository artifact'
      if: inputs.phase == 'prepare'
      shell: bash
      run: |
        pushd ~/.m2/repository
        find -path "./${group_id}/*" -exec tar -rf repository.tar {} \+
        popd
        mv ~/.m2/repository/repository.tar .

    - name: 'Upload sonar artifact'
      if: inputs.phase == 'prepare'
      uses: actions/upload-artifact@v4
      with:
        name: sonar-artifact
        path: |
          target.tar
          repository.tar
        if-no-files-found: error
        retention-days: 1
